- name: printing hello from play levl variables
  hosts: localhost
  vars:
    text: hello world from play
  tasks:
    - name: printing hello
      ansible.builtin.debug:
        msg: "{{ text }}"

- name: printing hello from task level variables
  hosts: localhost
  tasks:
    - name: print hello
      vars:
        text: hello world
      ansible.builtin.debug:
        msg: "{{ text }}"

- name: printing hello from file level variables
  hosts: localhost
  vars_files:
    - variables.yml

  tasks:
    - name: print hello
      ansible.builtin.debug:
        msg: "{{ text }}"

- name: printing hello from cli level
  hosts: localhost
  tasks:
    - name: hello
      ansible.builtin.debug:
        msg: "{{ text }}"

