groups:
- name: roboshop
  rules:
  - alert: cpu utilization
    expr: 100 - ( avg by (instance_name) (rate(node_cpu_seconds_total{mode='idle'}[1m]))* 100) > 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: cpu utilization is high