- name: learning about variables
  hosts: localhost
  vars:
    url: hello.com from play level
  tasks:
    - name: printing variables
      ansible.builtin.debug:
        msg: "{{ url }}"

- name: learning about variables
  hosts: localhost
  tasks:
    - name: printing variables
      vars:
        url: hello.com from task level
      ansible.builtin.debug:
        msg: "{{ url }}"

- name: learning about variables
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: printing variables
      ansible.builtin.debug:
        msg: "{{ url }}"

- name: learning about variables
  hosts: localhost
  tasks:
    - name: printing variables
      ansible.builtin.debug:
        msg: "{{ url }}"