- name: Install prometheus
  ansible.builtin.import_tasks:
    file: prometheus.yml
  when: prometheus_server

- name: Install node exporter
  ansible.builtin.import_tasks:
    file: node_exporter.yml
  when: node_exporter

- name: update scrape_configs of prometheus.yml file
  ansible.builtin.import_tasks:
    file: prometheus_config.yml
  when: prometheus_config

- name: update alertmanager configuration
  ansible.builtin.import_tasks:
    file: alertmanager_config.yml
  when: alertmanager