- name: create prometheus directory
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory

- name: installing prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.47.1/prometheus-2.47.1.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: yes

- name: configure systemd file
  ansible.builtin.copy:
    src: prometheus.service
    dest: /etc/systemd/system/

- name: enable and start prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started


