- name: update prometheus.yml file
  ansible.builtin.template:
    src: config.yml
    dest: /opt/{{ prometheus_dir }}/prometheus.yml

- name: update alerts file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/{{ prometheus_dir }}/{{ item }}
  loop:
    - {{ alert_files }}

- name: enable and start prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    daemon_reload: true
    state: restarted

- name: check prometheus is started or not
  ansible.builtin.shell: netstat -lntp | grep 9090