- name: update prometheus.yml file
  ansible.builtin.template:
    src: config.yml
    dest: /opt/{{ prometheus_dir }}/prometheus.yml

- name: update server_status file
  ansible.builtin.template:
    src: server-status.yml
    dest: /opt/{{ prometheus_dir }}/server_status.yml

- name: enable and start prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    daemon_reload: true
    state: restarted

- name: check prometheus is started or not
  ansible.builtin.shell: netstat -lntp | grep 9090