- name: add application user
  ansible.builtin.user:
    name: roboshop

- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download code to app directory
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/"{{ component }}.zip
    dest: /app
    remote_src: yes


