- name: execute mongodb block
  block:
    - name: setup mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: installed

    - name: load schema
      ansible.builtin.shell: mongo --host {{ lookup('amazon.aws.aws_ssm', '{{env}}.mongodb_url', region='us-east-1') }} </app/schema/{{ component }}.js
  when: schema_type == "mongo"

- name: execute mysql block
  block:
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql
        state: installed

    - name: load schema
      ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.mysql_host', region='us-east-1') }} -u{{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.mysql_user', region='us-east-1') }} -p{{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.mysql_pass', region='us-east-1') }} < /app/schema/"{{ component }}".sql

  when: schema_type == "mysql"

