- name: install redis repo file
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    disable_gpg_check: true
    state: installed


- name: install redis
  ansible.builtin.dnf:
    name: redis
    enablerepo: remi-6.2
    state: installed

- name: Update listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: enable and start redis
  ansible.builtin.systemd:
    name: redis
    enabled: true
    state: started