- name: install redis repo file
  ansible.builtin.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    disable_gpg_check: true
    state: installed

- name: enable redis6.2
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y


- name: install redis
  ansible.builtin.dnf:
    name: redis
    state: installed